table! {
    /// Representation of the `accounts` table.
    ///
    /// (Automatically generated by Diesel.)
    accounts (id, thirdParty) {
        /// The `id` column of the `accounts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `thirdParty` column of the `accounts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        thirdParty -> Text,
        /// The `insertedAt` column of the `accounts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        insertedAt -> Text,
        /// The `modifiedAt` column of the `accounts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        modifiedAt -> Text,
        /// The `version` column of the `accounts` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Integer,
    }
}

table! {
    /// Representation of the `thirdParties` table.
    ///
    /// (Automatically generated by Diesel.)
    thirdParties (id) {
        /// The `id` column of the `thirdParties` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `insertedAt` column of the `thirdParties` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        insertedAt -> Text,
        /// The `modifiedAt` column of the `thirdParties` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        modifiedAt -> Text,
        /// The `version` column of the `thirdParties` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Integer,
    }
}

joinable!(accounts -> thirdParties (thirdParty));

allow_tables_to_appear_in_same_query!(
    accounts,
    thirdParties,
);
