table! {
    /// Representation of the `accounts` table.
    ///
    /// (Automatically generated by Diesel.)
    accounts (id, thirdParty) {
        /// The `id` column of the `accounts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `thirdParty` column of the `accounts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        thirdParty -> Text,
        /// The `insertedAt` column of the `accounts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        insertedAt -> Text,
        /// The `modifiedAt` column of the `accounts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        modifiedAt -> Text,
        /// The `version` column of the `accounts` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Integer,
    }
}

table! {
    /// Representation of the `applications` table.
    ///
    /// (Automatically generated by Diesel.)
    applications (id) {
        /// The `id` column of the `applications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `description` column of the `applications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `insertedAt` column of the `applications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        insertedAt -> Text,
        /// The `modifiedAt` column of the `applications` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        modifiedAt -> Text,
        /// The `version` column of the `applications` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Integer,
    }
}

table! {
    /// Representation of the `emailAddresses` table.
    ///
    /// (Automatically generated by Diesel.)
    emailAddresses (id) {
        /// The `id` column of the `emailAddresses` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `insertedAt` column of the `emailAddresses` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        insertedAt -> Text,
        /// The `modifiedAt` column of the `emailAddresses` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        modifiedAt -> Text,
        /// The `version` column of the `emailAddresses` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Integer,
    }
}

table! {
    /// Representation of the `emailReportSubscriptions` table.
    ///
    /// (Automatically generated by Diesel.)
    emailReportSubscriptions (report, account, thirdParty, application) {
        /// The `report` column of the `emailReportSubscriptions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        report -> Text,
        /// The `account` column of the `emailReportSubscriptions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        account -> Text,
        /// The `thirdParty` column of the `emailReportSubscriptions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        thirdParty -> Text,
        /// The `application` column of the `emailReportSubscriptions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        application -> Text,
        /// The `address` column of the `emailReportSubscriptions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        address -> Text,
        /// The `insertedAt` column of the `emailReportSubscriptions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        insertedAt -> Text,
        /// The `modifiedAt` column of the `emailReportSubscriptions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        modifiedAt -> Text,
        /// The `version` column of the `emailReportSubscriptions` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Integer,
    }
}

table! {
    /// Representation of the `emailReports` table.
    ///
    /// (Automatically generated by Diesel.)
    emailReports (id) {
        /// The `id` column of the `emailReports` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `description` column of the `emailReports` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
        /// The `insertedAt` column of the `emailReports` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        insertedAt -> Text,
        /// The `modifiedAt` column of the `emailReports` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        modifiedAt -> Text,
        /// The `version` column of the `emailReports` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Integer,
    }
}

table! {
    /// Representation of the `fileLocation` table.
    ///
    /// (Automatically generated by Diesel.)
    fileLocation (purpose, account, thirdParty, forReading, forWriting) {
        /// The `purpose` column of the `fileLocation` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        purpose -> Text,
        /// The `account` column of the `fileLocation` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        account -> Text,
        /// The `thirdParty` column of the `fileLocation` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        thirdParty -> Text,
        /// The `forReading` column of the `fileLocation` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        forReading -> Integer,
        /// The `forWriting` column of the `fileLocation` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        forWriting -> Integer,
        /// The `folder` column of the `fileLocation` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        folder -> Text,
        /// The `fileName` column of the `fileLocation` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        fileName -> Text,
        /// The `insertedAt` column of the `fileLocation` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        insertedAt -> Text,
        /// The `modifiedAt` column of the `fileLocation` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        modifiedAt -> Text,
        /// The `version` column of the `fileLocation` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Integer,
    }
}

table! {
    /// Representation of the `fileLocationPurposes` table.
    ///
    /// (Automatically generated by Diesel.)
    fileLocationPurposes (id) {
        /// The `id` column of the `fileLocationPurposes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `insertedAt` column of the `fileLocationPurposes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        insertedAt -> Text,
        /// The `modifiedAt` column of the `fileLocationPurposes` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        modifiedAt -> Text,
        /// The `version` column of the `fileLocationPurposes` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Integer,
    }
}

table! {
    /// Representation of the `thirdParties` table.
    ///
    /// (Automatically generated by Diesel.)
    thirdParties (id) {
        /// The `id` column of the `thirdParties` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `insertedAt` column of the `thirdParties` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        insertedAt -> Text,
        /// The `modifiedAt` column of the `thirdParties` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        modifiedAt -> Text,
        /// The `version` column of the `thirdParties` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version -> Integer,
    }
}

joinable!(accounts -> thirdParties (thirdParty));
joinable!(emailReportSubscriptions -> applications (application));
joinable!(emailReportSubscriptions -> emailAddresses (address));
joinable!(emailReportSubscriptions -> emailReports (report));
joinable!(emailReportSubscriptions -> thirdParties (thirdParty));
joinable!(fileLocation -> fileLocationPurposes (purpose));
joinable!(fileLocation -> thirdParties (thirdParty));

allow_tables_to_appear_in_same_query!(
    accounts,
    applications,
    emailAddresses,
    emailReportSubscriptions,
    emailReports,
    fileLocation,
    fileLocationPurposes,
    thirdParties,
);
