-- Your SQL goes here
insert into fileLocationPurposes ("id") values 
('orders'), 
('orderRequests'),
('orderResponses'),
('customers'),
('customerRequests'),
('customerResponses'),
('customersCreate'),
('customersUpdate'),
('customerAcknowledgments'),
('customerStatusChecks'),
('customerStatusInterpretations'),
('styles'),
('stylesCreate'),
('stylesUpdate'),
('styleRequests'),
('styleResponses'),
('stylesAcknowledgments'),
('stylesStatusChecks'),
('stylesStatusInterpretations'),
('inventory'),
('inventoryRequests'),
('inventoryResponses'),
('inventoryAcknowledgment'),
('inventoryStatusCheck'),
('inventoryStatusInterpretations'),
('priceSheets'),
('priceSheetRequests'),
('priceSheetResponses'),
('pricesheetAcknowledgments'),
('pricesheetStatusChecks'),
('pricesheetStatusInterpretations');

