CREATE TABLE accounts (
  id TEXT NOT NULL,
  thirdParty TEXT NOT NULL REFERENCES thirdParties (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  insertedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT a2 PRIMARY KEY (id, thirdParty),
  CONSTRAINT a2 UNIQUE (id, thirdParty)
);

