CREATE TABLE emailAddresses (
  id TEXT NOT NULL PRIMARY KEY ASC UNIQUE,
  insertedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE emailReports (
  id TEXT NOT NULL PRIMARY KEY ASC UNIQUE,
  description TEXT NOT NULL default "",
  insertedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE applications (
  id TEXT NOT NULL PRIMARY KEY ASC UNIQUE,
  description TEXT NOT NULL default "",
  insertedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE emailReportSubscriptions (
  report TEXT NOT NULL REFERENCES emailReports (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  account TEXT NOT NULL REFERENCES accounts (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  thirdParty TEXT NOT NULL REFERENCES thirdParties (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  application TEXT NOT NULL REFERENCES applications (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  address TEXT NOT NULL REFERENCES emailAddresses (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  insertedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT e1 PRIMARY KEY (report, account, thirdParty, application)
);
