CREATE TABLE thirdParties (
  id TEXT NOT NULL PRIMARY KEY ASC UNIQUE,
  insertedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modifiedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version INTEGER NOT NULL DEFAULT 0
);
 

